<div id="checkout-step-pas" class="pas-use step-content row" data-role="content">
    <div class="control pas col-method">
        <input type='radio' class="radio" id="pas-yes" <?php if ($block->getStorePickupActivatedDefault() === "1") echo 'checked="checked"'; ?> onclick="PickupAtStore.showPickupAtStore(true)" name='pickupatstore' value='1'/>
        <label class="label" for="pas-yes"><span class="ico"></span><span><?php echo __("Recoger en Tienda"); ?></span></label>
    </div>
    <div class="control nopas">
        <input type='radio' id="pas-no" <?php if ($block->getStorePickupActivatedDefault() !== "1") echo 'checked="checked"'; ?> onclick="PickupAtStore.showPickupAtStore(false)"  name='pickupatstore' value='0'/>
        <span><?php echo __("No"); ?></span>
    </div>
</div>
