<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ppsoft\Level2\Block\Level2 $block */

$catchild = $block->getCategoryChilds();
$current = $block->getCurrentCategory();
$description = $block->getCurrentCategory()->getDescription();
$arrayCat = array();
foreach ($catchild as $cat)
{
    $arrayCat = $cat->getName();
}
?>
<div class="all-categories">
    <div class="title-main">
        <span><?php /* @escapeNotVerified */ echo __('Línea Blanca'); ?></span>
    </div>
    <div class="banner">
        <img src="<?php echo $this->getViewFileUrl('images/bannerlineablanca.jpg'); ?>" alt="lineablanca">
    </div>
    <ul class="sub-categorias">
        <?php foreach ($catchild as $cchild): ?>
            <?php $catloaded = $block->getLoadedCategory($cchild->getId()); ?>
        <li>
            <a href="<?= /* @escapeNotVerified */ $cchild->getUrl() ?>" class="child-url"> 
                <?php if ($catloaded->getImageUrl()) : ?>
                    <img class="img-cat" src="<?php  echo $catloaded->getImageUrl(); ?>" />
                <?php endif; ?>
            </a>
            <a href="<?= /* @escapeNotVerified */ $cchild->getUrl() ?>" class="child-url">
                <span class="first-child"><?php /* @escapeNotVerified */ echo __($cchild->getName());?></span>
            </a>
            <?php $catgrandchild = $block->getCategoryGrandChilds($cchild->getId()) ?>
            <?php foreach ($catgrandchild as $grandchild): ?>
                <a href="<?= /* @escapeNotVerified */ $grandchild->getUrl() ?>" class="grandchild-url">
                    <span class="grand-child"><?php /* @escapeNotVerified */ echo __($grandchild->getName());?></span>
                </a>
            <?php endforeach; ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php if ($_description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="description">
        <span class="title">
            <?= __('Descripción') ?>
        </span>
        <span class="content">
           <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
        </span>
    </div>
<?php endif; ?>
