<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ppsoft\Level2\Block\Zona $block */

$products = $block->getProducts();
$category = $block->getCategory();

?>
<?php foreach ($products as $product): ?>
    <?php $arraycat = $product->getCategoryIds(); ?>
<?php if($product->getData('label_product')): ?>
     <?php
        if(!in_array($block->getCategory(), $arraycat)):
        array_push($arraycat, $category);
        /*
                $block->addCategory($product->getSku(),  $product->getCategoryIds());*/
        //not working with dependency injection, already implemented in Zona.php block and not working
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $categoryLinkRepository = $objectManager->get('\Magento\Catalog\Api\CategoryLinkManagementInterface');
        $categoryLinkRepository->assignProductToCategories($product->getSku(), $arraycat);

        endif; ?>
<?php endif; ?>
<?php endforeach; ?>

