<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
 if ($product->getSpecialPrice())
{ $number = number_format($product->getSpecialPrice(), '2', '.', ',');
    $split = explode (".", $number);
    $integer = $split[0];
    $decimal = $split[1];
}
else {
    $number = number_format($product->getPrice(), '2', '.', ',');
    $split = explode (".", $number);
    $integer = $split[0];
    $decimal = $split[1];
    if ($product->getTypeId() == 'configurable')
    {
        $number = number_format($product->getFinalPrice(), '2', '.', ',');
        $split = explode (".", $number);
        $integer = $split[0];
        $decimal = $split[1];
    }
}
?>
<div class="product-name">
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
    <div class="precio">
        <span class="alcontado">Contado &nbsp;</span><span class="int"><?php echo $block->getCurrentCurrencySymbol() .'.&nbsp;' . $integer?>.</span><span class="decimal"><?php echo $decimal;?></span>
    </div>
</div>
