<?php
/**
 * Copyright © 2018 Wagento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<script>
    require([
        'jquery',
        'domReady!',
        'slick'
    ], function($){
        $(document).ready(function(){
            $('.banners-home-mobile').slick({
                dots: true,
                infinite: true,
                speed: 300,
                arrows: false,
                slidesToShow: 1,
                autoplaySpeed: 3000,
                adaptiveHeight: true
            });
        });
    });
</script>