<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ppsoft\Home\Block\RecentProduct $block */

$collection = $block->getProductCollection()->addFieldToFilter('added_at')->setOrder('added_at', 'desc')->setPageSize(7);
$productDuplicate = array();
$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
?>
<div class="reciente desktop">
    <span class="title">
    <?php /* @escapeNotVerified */ echo __('Visto recientemente') ?>
    </span>
</div>
<div class="recent-slider vistos-slider desktop">
    <?php foreach ($collection as $item): ?>
        <?php  $productid =$item->getProductId();
        if (!in_array($productid, $productDuplicate)):
            array_push($productDuplicate,$productid);
            $products = $block->getLoadProduct($productid);
        ?>
        <div class="recent-container">
            <a class="img-product" href="<?= /* @escapeNotVerified */ $products->getProductUrl() ?>" ><img src="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Image')->init($products, 'category_page_list')->setImageFile($products->getImage())->getUrl(); ?>" width="240" height="300" /> </a>
            <strong class="product-item-name">
                    <a title="<?= $block->escapeHtml($products->getName()) ?>"
                       href="<?= /* @escapeNotVerified */ $products->getProductUrl() ?>"
                       class="product-item-link" id="item-name">
                        <?= $block->escapeHtml($products->getName()) ?>
                    </a>
            </strong>
            <div class="sku-container sku">
                <span class="sku value">
                        <?= $block->escapeHtml($products->getSku()) ?>
                    </span>
            </div>
            <div class="cuotos-price">
                <?php
                $number = number_format($products->getPrice(), '2', '.', ',');
                $split = explode (".", $number);
                $integer = $split[0];
                $decimal = $split[1];

                if ($products->getSpecialPrice()) {
                    $numberSpecial = number_format($products->getSpecialPrice(), '2', '.', ',');
                    $splitSpecial = explode (".", $numberSpecial);
                    $integerSpecial = $splitSpecial[0];
                    $decimalSpecial = $splitSpecial[1];
                }
                ?>

                <div class="price-before">
                    <?php if($products->getSpecialPrice()):?>
                        <span class="price-currency"><p class="antes">Antes:</p>&nbsp;<?= __('%1. %2.<span class="decimal">%3</span>',$block->getCurrentCurrencySymbol(), $integer, $decimal) ?></span>
                    <?php endif; ?>
                </div>

                <div class="price-now">
                            <span class="alcontado">
                                <?= __('Ahora:&nbsp;') ?>
                            </span>
                    <span class="int"><?php echo __('Bs.'); ?><?php echo ($products->getSpecialPrice() ? $integerSpecial : $integer) ?>.</span>
                    </span>
                    <span class="decimal">
                        <?php echo ($products->getSpecialPrice() ? $decimalSpecial : $decimal) ?>
                    </span>
                </div>


            </div>
        
            <!--show icon shipping-->
            <!--end show icon shipping-->

                <div class="cart">
                    <?php $postParams = $block->getAddToCartPostParams($products); ?>
                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                        <?php echo $block->getBlockHtml('formkey')?>
                        <button type="submit"
                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                class="action tocart primary">
                            <span><?php /* @escapeNotVerified */ echo __('Agregar Al Carrito >') ?></span>
                        </button>
                    </form>
                </div>
        </div>
          <?php endif; ?>
    <?php endforeach; ?>
</div>
<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                   "bindSubmit": true
                 }
            }
        }
 </script>
<script>
    require([
        'jquery',
        'domReady!',
        'slick'
    ], function($){
        $(document).ready(function(){
            $('.vistos-slider').slick({
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                responsive: [
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 1,
                            dots: false,
                            prevArrow: true,
                            nextArrow: true
                        }
                    },
                    {
                        breakpoint: 1200,
                        settings: {
                            slidesToShow: 3
                        }
                    }
                ]
            });
        });
    });
</script>