<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 */
/* @var $block \Magento\CustomAttributeManagement\Block\Form\Renderer\Select */
?>
<?php
$fieldCssClass = 'field field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
$fieldCssClass .= $block->getFieldName() == 'pos_tipodocumentoid' ? ' required' : '';
$requiredInput = $block->getFieldName() == 'pos_tipodocumentoid' ? ' required-entry':'';

$extraField = '';
$extraField .= $block->getFieldName() == 'pos_tipodocumentoid' ? '  tabindex="5"' : '';
?>
<div class="<?= /* @escapeNotVerified */ $fieldCssClass ?>">
    <label class="label" for="<?= $block->getHtmlId() ?>"><span><?= /* @escapeNotVerified */ $block->getLabel() ?></span></label>
    <div class="control">
        <select id="<?= $block->getHtmlId() ?>" class="<?= $requiredInput ?>" name="<?= /* @escapeNotVerified */ $block->getFieldName() ?>"<?php if ($block->getHtmlClass()):?> class="select <?= $block->getHtmlClass() ?><?= $requiredInput ?>"<?php endif;?><?= $extraField ?>>
            <?php foreach ($block->getOptions() as $option):?>
                <option value="<?= /* @escapeNotVerified */ $option['value'] ?>"<?php if ($option['value'] == $block->getValue()):?> selected="selected"<?php endif;?>><?= $block->escapeHtml($option['label']) ?></option>
            <?php endforeach;?>
        </select>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?= /* @escapeNotVerified */ $_message ?></div>
        <?php endif; ?>
    </div>
</div>