<div class="devolucion">
    <div class="left"><img src="<?php echo $this->getViewFileUrl('images/logodevolucion.png'); ?>" alt="devolucion icon"></div>
    <div class="right"><span class="text first">Compra tranquilo,</span>
    <span class="text second">lo puedes cambiar o devolver.</span>&nbsp;
    <a href="<?php echo $this->getUrl('cambios-y-devoluciones.html') ?>">Ver detalles</a>
    </div>
</div>