<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<div class="mobile name-container">
    <span class="name-mobile">
        <?= $_product->getName(); ?>
    </span>
    <span class="sku-mobile">
        <?= $_product->getSku(); ?>
    </span>
</div>

