<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$_imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$_serviceHelper = $this->helper('Ppsoft\SalesEmail\Helper\ProductService');

if ($childProd = current($_item->getChildrenItems())) {
    $productImage = $_imageHelper->init($childProd->getProduct(), 'category_page_list', ['height' => 50 , 'width'=> 79])->getUrl();
} else {
    $productImage = $_imageHelper->init($_item->getProduct(), 'category_page_list', ['height' => 50 , 'width'=> 79])->getUrl();
}
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <table>
            <tbody>
            <tr>
                <td class="item-img" width="80px" style="width: 80px;"><img src="<?= $_imageHelper->init($_item->getProduct(), 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('79','50')->getUrl();?>" alt="<?= $block->escapeHtml($_item->getName()) ?>" style="width: 60px; height: auto;" /></td>
                <td class="item-info">
                    <p class="product-name">
                        <?= $block->escapeHtml($_item->getName()) ?>
                    </p>
                    <p class="product-requirement">
                        <?php
                        $service = $_serviceHelper->getService($_item->getProductId());
                        if(!empty($service)):
                            ?>
                            <a href="<?php echo $_serviceHelper->getStoreBaseUrl(). "cms/{$service['file']}"?>" target="_blank">
                                <strong>Clic aquí para revisar los requisitos de instalación.</strong>
                            </a>
                        <?php endif;?>
                    </p>
                    <p class="sku"><?= $block->escapeHtml($block->getSku($_item)) ?></p>
                </td>
            </tr>
            </tbody>
        </table>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
