<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<li class="back back-cart mobile">
    <!--a class="arrow-back" href="javascript:history.go(-1)">Atrás</a!-->
    <span class="carrito"><?php echo __('Mi Carrito') ?></span>
    <!--img class="micarrito" src="<?php echo $this->getViewFileUrl('images/micarrito.png'); ?>" alt="carrito icon"!-->
    <span id="editar"></span>
</li>

