<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="cart-text desktop">
    <?php
    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cart-text')->toHtml();
    ?>
    <div class="cart-button">
        <a class="go-checkout" href="<?php echo $block->getUrl('checkout/index'); ?>">
            <?php echo __('Comprar Ahora>') ?>
        </a>
    </div>
</div>