<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Ppsoft\Home\Block\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');

$compareList = $this->helper('Magento\Catalog\Helper\Product\Compare');
$compareRemove = $this->helper('Ppsoft\Compare\Helper\Product\Compare');
$compareArray = [];
foreach ($compareList->getItemCollection() as $item) {
    $compareArray[$item->getSku()] = $item;
}
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php $category ='';
    if (!empty($block->getCurrentCategory())):
        $category = $block->getCurrentCategory()->getName();
    endif; ?>
    <div class="mobile cat-name"> <span><?= $category ?></span></div>
    <div class="mobile toolbar-mobile"> <?= $block->getToolbarHtml() ?></div>
    <div class="recent-slider products-category">
        <?php foreach ($_productCollection as $products): ?>

            <?php  $productid =$products->getProductId(); ?>
            <?php  $label =$products->getData('label_product');
            $class = '';
            switch ($label) {
                case 'Aun mas bajo':
                    $class = 'bajo';
                    break;
                case 'Precio Imbatible':
                    $class = 'imbatible';
                    break;
                case 'Oportunidad Unica':
                    $class = 'oportunidad';
                    break;
                case 'Combo Ahorro':
                    $class = 'imbatible';
                    break;
                case 'Producto Nuevo':
                    $class = 'nuevo';
                    break;
                case 'Nuevo Producto':
                    $class = 'nuevo';
                    break;

            }

            ?>
            <div class="recent-container">
                <?php  if ($products->getSpecialPrice()): ?>
                    <div class="promo">
                            <span>
                                <?php /* @escapeNotVerified */ echo __('OFERTA ESPECIAL'); ?>
                            </span>
                        <img src='<?php echo $this->getViewFileUrl('images/oferta-especial.png'); ?>' alt="promo">
                    </div>
                <?php endif; ?>
                <?php  if ($class): ?>
                    <img class="<?= $class; ?>" src='<?php echo $this->getViewFileUrl('images/' . $class .'.png'); ?>' alt="precios">
                <?php endif; ?>
                <a class="img-product" href="<?= /* @escapeNotVerified */ $products->getProductUrl() ?>" ><img src="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Image')->init($products, 'category_page_list')->setImageFile($products->getImage())->getUrl(); ?>" /> </a>
                <strong class="product-item-name desktop">
                    <a title="<?= $block->escapeHtml($products->getName()) ?>"
                       href="<?= /* @escapeNotVerified */ $products->getProductUrl() ?>"
                       class="product-item-link" id="item-name">
                        <?= $block->escapeHtml($products->getName())?>
                    </a>
                </strong>
                <strong class="product-item-name mobile">
                    <a title="<?= $block->escapeHtml($products->getName()) ?>"
                       href="<?= /* @escapeNotVerified */ $products->getProductUrl() ?>"
                       class="product-item-link" id="item-name">
                        <?= $block->escapeHtml($products->getName()) ?>
                    </a>
                </strong>
                <div class="sku-container sku">
                        <span class="sku value">
                        <?= $block->escapeHtml($products->getSku()) ?>
                    </span>
                </div>
                <div class="cuotos-price">
                    <?php
                    $number = number_format($products->getPrice(), '2', '.', ',');
                    $split = explode (".", $number);
                    $integer = $split[0];
                    $decimal = $split[1];

                    if ($products->getSpecialPrice()) {
                        $numberSpecial = number_format($products->getSpecialPrice(), '2', '.', ',');
                        $splitSpecial = explode (".", $numberSpecial);
                        $integerSpecial = $splitSpecial[0];
                        $decimalSpecial = $splitSpecial[1];
                    }
                    ?>

                    <div class="price-before">
                        <?php if($products->getSpecialPrice()):?>
                            <span class="price-currency"><p class="antes">Antes:</p>&nbsp;<?= __('%1. %2.<span class="decimal">%3</span>',$block->getCurrentCurrencySymbol(), $integer, $decimal) ?></span>
                        <?php endif; ?>
                    </div>

                    <div class="price-now">
                            <span class="alcontado">
                                <?= __('Ahora:&nbsp;') ?>
                            </span>
                        <span class="int"><?php echo __('Bs.'); ?><?php echo ($products->getSpecialPrice() ? $integerSpecial : $integer) ?>.</span>
                        </span>
                        <span class="decimal">
                                <?php echo ($products->getSpecialPrice() ? $decimalSpecial : $decimal) ?>
                            </span>
                    </div>
                    <?php
                    $cuota_uno =   $products->getData('minicuota_cuota_uno');
                    $monto_uno =   $products->getData('minicuota_monto_uno');
                    $cuota_dos =   $products->getData('minicuota_cuota_dos');
                    $monto_dos =   $products->getData('minicuota_monto_dos');
                    $cuota_tres =   $products->getData('minicuota_cuota_tres');
                    $monto_tres =   $products->getData('minicuota_monto_tres');
                    $cuota_inicial =   $products->getData('cuota_inicial');
                    ?>
                    <?php if ($cuota_inicial): ?>
                    <img class="minicuotas" src="<?php echo $this->getViewFileUrl('images/minicuotashigh.png'); ?>" alt="cuotas icon">
                </div>
                <div class="cuote-wrap">
                    <?php endif; ?>
                    <?php  /* if ($cuota_uno && $monto_uno): ?>
                            <div class="cuote-price">
                                <?php
                                $number = number_format($monto_uno, '2', '.', ',');
                                $split = explode(".", $number);
                                $integer = $split[0];
                                $decimal = $split[1]; ?>
                                <span style="visibility: hidden; position: absolute;" class="pixel-price"><?php echo $integer;?></span>
                                <span class="price-currency int"><span class="bs"><?php echo __('Bs'); ?></span><?= $integer ?>.</span>
                                <span class="price-currency int"><?= $integer ?>.</span>
                                <span class="decimal"><?php echo $decimal; ?></span>
                                <span class="cuote-month"><?= $cuota_uno ?> <span class="cuote-mulitply"><?php echo __('x '); ?></span></span>
                                <span class="cuote-permonth"><?php echo __('por mes'); ?></span>
                            </div>
                        <?php endif; */  ?>
                    <?php /* if ($cuota_dos && $monto_dos): ?>
                            <div class="cuote-price">
                                <?php
                                $number = number_format($monto_dos, '2', '.', ',');
                                $split = explode(".", $number);
                                $integer = $split[0];
                                $decimal = $split[1]; ?>
                                <span class="cuote-month"><?= $cuota_dos ?> <span class="cuote-mulitply"><?php echo __('x '); ?></span></span>
                                <span class="price-currency int"><?= $block->getCurrentCurrencySymbol() . '.&nbsp;' . $integer ?>.</span>
                                <span class="decimal"><?php echo $decimal; ?></span>
                                <span class="cuote-permonth"><?php echo __('por mes'); ?></span>
                            </div>
                        <?php endif; */ ?>

                    <?php if ($cuota_tres && $monto_tres): ?>
                        <div class="cuote-price list">
                            <?php
                            $number = number_format($monto_tres, '2', '.', ',');
                            $split = explode(".", $number);
                            $integer = $split[0];
                            $decimal = $split[1]; ?>
                            <span style="visibility: hidden; position: absolute;" class="pixel-price"><?php echo $integer;?></span>
                            <span class="price-currency int"><span class="bs"><?php echo __('Bs.'); ?></span>&nbsp;<?= $integer ?>.</span>
                            <sup class="decimal"><?php echo $decimal; ?></sup>&nbsp;
                            <span class="cuote-month"><span class="cuote-mulitply">&nbsp;<?php echo __('x'); ?>&nbsp;</span><?= $cuota_tres ?><span class="months">&nbsp;<?php echo __('meses'); ?></span></span>
                        </div>
                    <?php endif; ?>
                    <?php if ($cuota_inicial): ?>
                        <div class="cuote-price inicial list">
                            <?php
                            $number = number_format($cuota_inicial, '2', '.', ',');
                            $split = explode(".", $number);
                            $integer = $split[0];
                            $decimal = $split[1]; ?>
                            <span class="cuota-inicial"><?php echo __('Inicial:'); ?></span>
                            <span class="price-currency"><?= __('Bs.')?><?= $integer ?>.</span>
                            <sup class="decimal"><?php echo $decimal; ?></sup>
                        </div>
                    <?php endif; ?>

                </div>


                <!--show icon shipping-->
                <?php
                $codigos = false;
                if($products->getCustomAttribute('disponibilidad')) {
                    $disponibilidad = $products->getCustomAttribute('disponibilidad')->getValue();
                    $codigos = $block->availableAlmacenes($disponibilidad);
                }
                ?>
                <?php
                $cuarentena = '';
                $isInStock = true;
                switch ($codigos) {
                    case 1:
                        $iconHomeDelivery = $this->getViewFileUrl('images/shiping/deliver-green-category-icon.svg');
                        $homeDelivery = __('<span style="color:#00B41A;">Disponible</span> para envío a domicilio');

                        $iconPickUpStore = $this->getViewFileUrl('images/shiping/store-green-category-icon.svg');
                        $pickUpStore = __('<span style="color:#00B41A;">Disponible</span> para recojo en tienda');

                        $classHome = 'disponible';
                        $classPick = 'disponible';
                        break;
                    case 2:
                        $iconHomeDelivery = $this->getViewFileUrl('images/shiping/deliver-green-category-icon.svg');
                        $homeDelivery = __('<span style="color:#00B41A;">Disponible</span> para envío a domicilio');

                        $iconPickUpStore = $this->getViewFileUrl('images/shiping/store-grey-category-icon.svg');
                        $pickUpStore = __('<span style="color:#ec1f26;">No disponible</span> para recojo en tienda');

                        $classHome = 'disponible';
                        $classPick = 'no-disponible';
                        break;
                    case 3:
                        $iconHomeDelivery = $this->getViewFileUrl('images/shiping/delivery-grey-category-icon.svg');
                        $homeDelivery = __('<span style="color:#ec1f26;">No disponible</span> para envío a domicilio');

                        $iconPickUpStore = $this->getViewFileUrl('images/shiping/store-green-category-icon.svg');
                        $pickUpStore = __('<span style="color:#00B41A;">Disponible</span> para recojo en tienda');

                        $classHome = 'no-disponible';
                        $classPick = 'disponible';
                        $cuarentena = __('NO DISPONIBLE POR CUARENTENA');
                        break;
                    case 0:
                        $iconHomeDelivery = $this->getViewFileUrl('images/shiping/delivery-grey-category-icon.svg');
                        $homeDelivery = __('<span style="color:#ec1f26;">No disponible</span> para envío a domicilio');

                        $iconPickUpStore = $this->getViewFileUrl('images/shiping/store-grey-category-icon.svg');
                        $pickUpStore = __('<span style="color:#ec1f26;">No disponible</span> para recojo en tienda');

                        $classHome = 'no-disponible';
                        $classPick = 'no-disponible';
                        $cuarentena = __('NO DISPONIBLE POR CUARENTENA');
                        $isInStock = false;
                        break;
                }
                ?>
                <div class="entrega-gratuita">
                        <span class="content-img">
                            <img src="<?= $iconHomeDelivery ?>" alt="truck icon"/>
                        </span>
                    <span class="text first <?= $classHome ?>"><?= $homeDelivery; ?></span>
                </div>
                <div class="entrega-gratuita">
                        <span class="content-img">
                            <img src="<?= $iconPickUpStore ?>" alt="truck icon"/>
                        </span>
                    <span class="text first <?= $classPick ?>"><?= $pickUpStore; ?></span>
                </div>
                <div class="entrega-gratuita cuarentena">
                    <strong><?= $cuarentena ?></strong>
                </div>
                <!--end show icon shipping-->

                <div class="add-to-compare">
                    <?php
                    $classCompareClick = '';
                    if (array_key_exists($products->getSku(), $compareArray)) {
                        $classCompareClick =  ' class="clicked"';
                    }
                    ?>
                    <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getCompare($products) ?>'
                       id="compare-link-<?= $products->getId() ?>"
                       role="button"
                       class="action tocompare"><span> <?= /* @escapeNotVerified */ __('Comparar') ?></span>
                    </a>
                    <a style="display: none" href="#" data-post='<?= /* @escapeNotVerified */ $compareRemove->getPostDataRemove($products) ?>'
                       id="compare-remove-link-<?= $products->getId() ?>"
                       role="button"
                       class="action tocompare">
                        <span class="clicked" ><?= /* @escapeNotVerified */ __('Comparar') ?></span>
                    </a>
                    <script type="text/javascript">// <![CDATA[
                        require([
                            'jquery',
                        ], function ($) {
                            'use strict';

                            $(document).ready(function () {
                                var productId =  <?= $products->getId() ?>;
                                var comparisonId = "#compare-link-"+productId;
                                var comparisonRemoveId = "#compare-remove-link-"+productId;
                                $( comparisonRemoveId ).click(function() {
                                    $(comparisonId).show();
                                    $(comparisonRemoveId).css("display","none");
                                });
                                $( comparisonId ).click(function() {
                                    $(comparisonId).hide();
                                    $(comparisonRemoveId).css("display","block");

                                });
                            });
                        });
                        // ]]>
                    </script>
                </div>
                    
                <?php /*echo $block->getBlockHtml('catalog.compare.link') */?>
                <?php if ($isInStock): ?>
                    <div class="cart">
                        <?php $postParams = $block->getAddToCartPostParams($products); ?>
                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                            <input type="hidden" namef="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                            <?php echo $block->getBlockHtml('formkey')?>
                            <button type="submit"
                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                    class="action tocart primary">
                                <span><?php /* @escapeNotVerified */ echo __('Agregar Al Carrito >') ?></span>
                            </button>
                        </form>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="toolbar-botoom">
        <?= $block->getToolbarHtml() ?>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                   "bindSubmit": true
                 }
            }
        }
 </script>
<script type="text/javascript">
    //<![CDATA[
    require([
        'jquery'
    ], function ($) {
        $(".product-item-link").mouseover(function () {
            $(this).text($(this)[0].title);
            $(this).css('overflow','visible');
            $(this).css('-webkit-box-orient','inherit');

        });
        $(".product-item-link").mouseout(function () {
            var item = $(this);
            overrideProductName(item);
        });
        $(".img-product").mouseover(function () {
            var item = $(this).siblings().find(".product-item-link");
            item.text(item[0].title);
            item.css('overflow','visible');
            item.css('-webkit-box-orient','inherit');
        });
        $(".img-product").mouseout(function(){
            var item = $(this).siblings().find(".product-item-link");
            overrideProductName(item);

        });
        function overrideProductName(item) {
            item.text(item[0].title);
            item.css('overflow','hidden');
            item.css('-webkit-box-orient','vertical');
        }
    });
    //]]>
</script>
<?php
$ajaxUrl = $block->getUrl("compare/index/productids");
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/compare-list": {
                    "AjaxUrl": "<?php echo $ajaxUrl;?>"
                }
            }
        }
</script>