<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Comprar Ahora>'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-checkout">
        <div class="fieldset">
            <div class="actions">
                <a href="<?php echo $this->getUrl('gotocheckout', ['product_id' => $block->getProduct()->getId()])?>"
                        class="go-to-checkout">

                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </a>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
