<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="entrega-gratuita-mobile mobile">
    <div class="entrega-icon">
    <img src="<?php echo $this->getViewFileUrl('images/entrega_gratuita_mobile.png'); ?>" alt="truck icon">
    </div>
    <div class="entrega-text">
    <span class="text first"><?php echo __('Ordena hoy y recibe en las próximas 24 hrs') ?></span>
    <span class="text second"><?php echo __('Entrega gratuita en compras superiores a Bs. 1,399*') ?></span>
    </div>
</div>