<?php
/** @var  \Ppsoft\CustomCheckout\Block\Onepage\Success $block */
?>

<div class="information bank">
    <span><?= /* @escapeNotVerified */__('Esta es la información de la cuenta de Dismac para que puedas realizar tu pago a través de transferencia.') ?></span>
</div>
<div class="information">
    <div class="beneficiary">
        <span class="beneficiary-name"><?=  /* @escapeNotVerified */__('Beneficiario: ')  ?></span>
        <span><?=  /* @escapeNotVerified */__('Dismatec S.A.')  ?></span>
    </div>
    <div class="bank">
        <span class="bank-name"><?=  /* @escapeNotVerified */__('Institución Bancaria: ') ?></span>
        <span><?=  /* @escapeNotVerified */__('Banco Unión') ?></span>
    </div>
    <div class="number-account">
        <span class="account"><?=  /* @escapeNotVerified */__('No. de Cuenta: ') ?></span><br/>
        <span style="font-weight: bold;"><?=  /* @escapeNotVerified */__('10000031739656') ?><span><?=  /* @escapeNotVerified */__(' Moneda Nacional') ?></span></span><br/>
    </div>
    <div class="account-type">
        <span class="type"><?=  /* @escapeNotVerified */__('Tipo de Cuenta: ') ?></span>
        <span><?=  /* @escapeNotVerified */__('Cuenta Corriente') ?></span>
    </div>
    <div class="nit">
        <span class="type"><?=  /* @escapeNotVerified */__('NIT: ') ?></span>
        <span><?=  /* @escapeNotVerified */__('1027967025') ?></span>
    </div>
</div>
<div class="information important">
    <div class="important-container">
    <span class="reminder"><b>IMPORTANTE: </b> al momento de realizar su transferencia/deposito colocar en el campo de Referencia su número de pedido <b class="order-big-text"><?php echo $block->escapeHtml($block->getOrderId()); ?></b></span>
    </div>
</div>
<div class="information">
    <span><?= /* @escapeNotVerified */__("En caso de no haber colocado su número de pedido en la referencia de la transferencia por <b>favor enviar</b>&nbsp;su comprobante de pago al correo ecommercepagos@dismac.com.bo") ?></span>
    <br/>
    <br/>
    <span><?= /* @escapeNotVerified */__("Recuerda que solo tienes <b>12 hrs</b> para realizar tu <b>depósito o transferencia</b> y enviar los datos de tu transacción.") ?></span>
</div>
