<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
$selectQty = $_product->getExtensionAttributes()->getStockItem()->getQty();
if($block->getQtyConfig()) {
$qty = $block->getQtyConfig();
$selectQty = reset($qty);
}
?>
<?php $buttonTitle = __('Agregar a mi Carrito'); ?>
<?php if ($_product->isSaleable()): ?>
    <?php $_helperDismacPos = $this->helper('Ppsoft\DismacPos\Helper\Data'); ?>
    <?php $stockWyomind = json_decode($_helperDismacPos->stockWyomind()->getStockByProductIdAndStoreIds($_product->getId(), array($_product->getStore()->getStoreId()))); ?>
    <?php
    $selectQty = $stockWyomind->qty;
    if ($selectQty > 5) {
        $selectQty = 5;
    }
    ?>
    
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Cantidad:') ?></span></label>
                    <div class="control">
                        <select type="number"
                                name="qty"
                                id="qty"
                                value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                                title="<?= /* @escapeNotVerified */ __('Cantidad') ?>"
                                class="input-text qty"
                                data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        >
                            <?php
                            $i = 1 ?>
                            <?php do { ?>
                                <option class="option-qty" value="<?= $i ?>">
                                    <?= $i ?>
                                </option>
                                <?php $i++ ?>
                            <?php } while ($i <= $selectQty);
                            ?>
                        </select>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
