<?php
use Magento\Framework\App\Action\Action;

if ($exist = ($this->getBestsellerProduct() && $this->getBestsellerProduct()->getPageSize())) {
    $_productCollection = $this->getBestsellerProduct();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $showCart = true;
    $type = 'widget-new-grid';
    $image = 'category_page_grid';
    $productcount = $this->getProductLimit();
    $pos = $block->getPositioned();
    $viewMode = 'grid';
    $imageDisplayArea = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
}
?>
<?php if ($exist):?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $iterator = 1; $count = 0;  $parent_arr = Array();  ?>
            <?php foreach ($_productCollection as $item): ?>
            <?php 
            $parentIds = $block->configurableObj()->getParentIdsByChild($item->getProductId());

            if(isset($parentIds[0])) {
                $productIds = $parentIds[0]; //Configurable product ids here
                if (!in_array($productIds, $parent_arr)) { // Avoid Repetition Of Configurable product id
                    $parent_arr[] = $productIds;
                    $_product =  $block->productRepositoryObj()->getById($productIds);
                } else {
                    continue;
                }
            } else{
                $_product = $block->loadProduct($item->getProductId());
            }
            $count = $count+1;
            if ($count > $productcount) {
                continue;
            }
            ?>
                <li class="item product product-item">
                    <div class="product-item-info best2" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" id="wage-list-<?= $_product->getId() ?>" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div class="actions-secondary">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               class="action towishlist"
                                               id="towishlist-<?= /* @noEscape */ $_product->getId() ?>"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php echo $block->escapeHtml(__('Add to Wish List')); ?></span>
                                            </a>
                                            <script>
                                                require([
                                                    'jquery',
                                                    'mage/validation',
                                                    'domReady!'
                                                ], function($) {
                                                    'use strict';

                                                    var pid = '<?= /* @noEscape */ $_product->getId() ?>';
                                                    var dataForm = $('#wage-list-'+pid);
                                                    var ignore = null;

                                                    dataForm.mage('validation', {
                                                        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                                                    }).find('input:text').attr('autocomplete', 'off');

                                                    $('#towishlist-'+pid).on('click', function () {
                                                        var result = dataForm.validation('isValid'); //validates form and returns boolean
                                                        if (!result) {
                                                            return false;
                                                        }
                                                    });
                                                });
                                            </script>
                                        <?php endif; ?>
                                        <a href="#" data-post='<?php echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataParams($_product); ?>'
                                           role="button"
                                           class="action tocompare"><span><?php echo $block->escapeHtml(__('Add to Compare')); ?></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>

<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
</script>
<?php endif; ?>

<?php endif;?>