<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Ppsoft\Level2\Block\Level2 $block */

$categories = $block->getCategoryCollection(true, 2, false, false, true); ?>
<?php
$_blogHelper = $this->helper('Mageplaza\Blog\Helper\Data');
$blockCatId = $_blogHelper->getBlogConfig('general/blog_cat_id');
?>
<div class="custom-nav-sections">
    <ul class="level0 menu-top">
        <?php foreach ($categories as $category) :
            $catloaded = $block->getLoadedCategory($category->getId());
            $catchilds = $block->getCategoryGrandChilds($category->getId());
            ?>
            <li class="first-li child-<?= (is_array($catchilds) ? count($catchilds) : $catchilds->count()) ?>">
                <?php $catUrl = ($category->getId() == $blockCatId) ? $_blogHelper->getBlogUrl('') : $category->getUrl(); ?>
                <a href="<?= /* @escapeNotVerified */
                $catUrl ?>" class="top-cat-url">
                    <span class="first-level-child"><?php /* @escapeNotVerified */
                        echo __($category->getName()); ?></span>
                </a>
                <?php if ($catchilds) : ?>
                    <ul class="level1 menu-child-1">
                        <?php foreach ($catchilds as $child) :
                            $catgrandchilds = $block->getCategoryGrandChilds($child->getId());
                            $count = (is_array($catgrandchilds) ? count($catgrandchilds) : $catgrandchilds->count());
                            ?>
                            <?php if ($count == 0) : ?>
                            <li class="li-no-child">
                                <a href="<?= /* @escapeNotVerified */
                                $child->getUrl() ?>" class="cat-url">
                                    <span class="child-name"><?php /* @escapeNotVerified */
                                        echo __($child->getName()); ?></span>
                                </a>
                            </li>
                        <?php endif; ?>
                            <?php if ($count > 0) : ?>
                            <li class="li-first-child">
                                <a href="<?= /* @escapeNotVerified */
                                $child->getUrl() ?>" class="cat-url">
                                    <span class="child-name"><?php /* @escapeNotVerified */
                                        echo __($child->getName()); ?></span>
                                </a>
                                <?php if ($count > 0) : ?>
                                    <ul class="level2 menu-child-2">
                                        <?php foreach ($catgrandchilds as $grandchild) :
                                            ?>
                                            <li class="li-second-child">
                                                <a href="<?= /* @escapeNotVerified */
                                                $grandchild->getUrl() ?>" class="cat-url">
                                                    <span class="child-name"><?php /* @escapeNotVerified */
                                                        echo __($grandchild->getName()); ?></span>
                                                </a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>

        <?php endforeach; ?>
    </ul>
</div>
<script>
    require([
        'jquery',
        'domReady!',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $('.first-li').hover(function () {
                $(this).find('.menu-child-1').toggle();
                $(this).toggleClass('active-li');
            });
        });
    });
</script>